"""initial schema

Revision ID: ba7a79739cdb
Revises: 
Create Date: 2026-09-30 21:20:45.448036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ba7a79739cdb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_gyms_name', 'gyms', [sa.literal_column('lower(trim(name))')], unique=True)
    op.create_table('muscle_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_muscle_groups_name', 'muscle_groups', [sa.literal_column('lower(trim(name))')], unique=True)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_unit', sa.Enum('lbs', 'kg', 'plates', name='weight_unit'), server_default='lbs', nullable=False),
    sa.CheckConstraint('id = 1', name='ck_settings_single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    # The single settings row; default_unit falls back to its server default ('lbs').
    op.execute("INSERT INTO settings (id) VALUES (1)")
    op.create_table('lifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_lifts_muscle_group_name', 'lifts', ['muscle_group_id', sa.literal_column('lower(trim(name))')], unique=True)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_machines_gym_name', 'machines', ['gym_id', sa.literal_column('lower(trim(name))')], unique=True)
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lift_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('weight_value', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('weight_unit', sa.Enum('lbs', 'kg', 'plates', name='weight_unit'), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('approximate', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('performed_on', sa.Date(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('reps > 0', name='ck_sets_reps_positive'),
    sa.CheckConstraint('weight_value >= 0', name='ck_sets_weight_non_negative'),
    sa.ForeignKeyConstraint(['lift_id'], ['lifts.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sets_lift_id'), 'sets', ['lift_id'], unique=False)
    op.create_index(op.f('ix_sets_machine_id'), 'sets', ['machine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sets_machine_id'), table_name='sets')
    op.drop_index(op.f('ix_sets_lift_id'), table_name='sets')
    op.drop_table('sets')
    op.drop_index('uq_machines_gym_name', table_name='machines')
    op.drop_table('machines')
    op.drop_index('uq_lifts_muscle_group_name', table_name='lifts')
    op.drop_table('lifts')
    op.drop_table('settings')
    op.drop_index('uq_muscle_groups_name', table_name='muscle_groups')
    op.drop_table('muscle_groups')
    op.drop_index('uq_gyms_name', table_name='gyms')
    op.drop_table('gyms')
    # ### end Alembic commands ###
    sa.Enum(name='weight_unit').drop(op.get_bind(), checkfirst=True)
